version: '3.4'

networks:
  skynet:
    driver: bridge
    # ipam:
    #   driver: default
    #   config:
    #     - subnet: 192.168.0.0/24

services:
  arkam_service:
    hostname: arkam_service
    # image: node:12.16.3-slim
    build:
      context: .
      dockerfile: ./Dockerfile
    command: ['yarn', 'start']
    # command: ["./scripts/wait-for-it.sh", "logger:5010/", "yarn", "start"]
    # command: ["./scripts/wait-for-it.sh", "logger:5010/", "yarn", "prod"]
    # command:
    #   ["./scripts/wait-for-it.sh", "logger:5010/", "node", "build/server.prod.js"]
    # command:
    #   ["./scripts/wait-for-it.sh", "logger:5010/", "yarn", "test", "--watch"]
    volumes:
      - ./:/usr/arkam_service
      - /usr/arkam_service/node_modules
    ports:
      - '5000:5000'
    env_file:
      - .dev.env
    depends_on:
      - mango
    networks:
      - skynet

  mango:
    hostname: mango
    image: mongo:latest
    ports:
      - '27017:27017'
    volumes:
      - ./containers-data/db:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: super
      MONGO_INITDB_ROOT_PASSWORD: 0GsF9MpRi4DEJJn8YnDEKgT720sjjLqs3VC3T
    networks:
      - skynet
    logging:
      driver: none

  web:
    container_name: web
    build:
      context: .
      dockerfile: ./config/nginx/dockerfile
    networks:
      - skynet
    ports:
      - 192.168.0.94:9000:80
      - 0.0.0.0:443:443
    depends_on:
      - arkam_service
    volumes:
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./config/nginx/dararkam.at.conf:/etc/nginx/sites-available/dararkam.at.conf
      # - ./config/nginx/dararkam.at.conf:/etc/nginx/conf.d/dararkam.at.template
      # - ./config/nginx/letsencrypt.conf:/etc/nginx/nginxconfig.io/letsencrypt.conf
      # - ./config/nginx/security.conf:/etc/nginx/nginxconfig.io/security.conf
      # - ./config/nginx/general.conf:/etc/nginx/nginxconfig.io/general.conf
      # - ./config/nginx/proxy.conf:/etc/nginx/nginxconfig.io/proxy.conf
    command: [nginx-debug, '-g', 'daemon off;']
    # sudo ip addr add 192.168.144.4/24 dev wlp4s
